### ISSUE TITLE
Last Played not working?

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#4]
Log file here: https://hastebin.com/benowivunu.sql

This is happening to me in a Kodi instance with basically just IAGL and a skin, but it was happening before I had my skin as well.

It happens when trying to navigate directly to the Last Played section, as well as in a widget.

**Comment by zach-morris** [comment]
Fixed with [9b13d1d](https://github.com/zach-morris/plugin.program.iagl/commit/9b13d1d26e43750b155f81798d7bd8bdcf1a1ea8), thanks

**Comment by drinfernoo** [comment]
I downloaded from this repo, uninstalled and reinstalled the add-on, but am still getting this: https://hastebin.com/cawojusage.sql

**Comment by zach-morris** [comment]
Its not in the repo yet, just in the latest git.  I compile a number of changes before pushing a new version to the repository.  You can try the latest git by [cloning the latest available](https://github.com/zach-morris/plugin.program.iagl/archive/main.zip), but then you have to manually copy the files over.

**Comment by drinfernoo** [comment]
I downloaded the zip of the whole repo and installed it manually, not from the repo.

**Comment by drinfernoo** [comment]
I may have to try a fresh install... it just doesn't seem to be working for me.
